# Copyright (c) 2026 Achyuth Jayadevan <achyuth@jayadevan.in>
# SPDX-License-Identifier: MIT
# Licensed under the MIT License. See LICENSE in the repository root.

from __future__ import annotations

from pathlib import Path

from razorproof.models import ClaimKind, Evidence, EvidenceLevel, Finding, ProbeResult, Severity
from razorproof.repositories import Repository

from .common import ProbeTimer, line_number, read


def _source_evidence(repo: Repository, relative: str, needle: str, summary: str) -> Evidence:
    text = read(repo.path / relative)
    return Evidence(
        kind="official_source",
        summary=summary,
        detail=needle,
        path=f"{repo.name}/{relative}",
        line=line_number(text, needle),
        source_url=f"{repo.remote.removesuffix('.git')}/blob/{repo.commit}/{relative}",
    )


def _mcp(repo: Repository) -> list[Finding]:
    findings: list[Finding] = []
    refunds = read(repo.path / "pkg/razorpay/refunds.go")
    if 'ValidateAndAddRequiredFloat(payload, "amount")' in refunds and 'int(payload["amount"].(float64))' in refunds:
        findings.append(Finding(
            id="RP-MCP-REFUND-TRUNCATION",
            title="Refund tool silently truncates a fractional subunit amount",
            repo=repo.name,
            surface="create_refund MCP tool",
            invariant="Money in currency subunits is an integer and invalid fractions must be rejected, never changed.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public report found in the searched repository",
            commit=repo.commit,
            description="The tool accepts JSON Schema number, decodes float64, then casts to int before the SDK call.",
            impact="An invalid fractional-subunit request reaches the API with a different value instead of failing closed. The mutation is less than one subunit, so this is an input-integrity defect rather than a large-value loss claim.",
            counterexample="amount=100.75 -> SDK amount=100",
            proposed_fix="Validate and store an int64 before invoking the SDK; upgrade the MCP dependency and publish an integer schema when supported.",
            evidence=[
                _source_evidence(repo, "pkg/razorpay/refunds.go", 'ValidateAndAddRequiredFloat(payload, "amount")', "Amount is accepted as binary float"),
                _source_evidence(repo, "pkg/razorpay/refunds.go", 'int(payload["amount"].(float64))', "Float is silently cast to integer"),
            ],
            tags=["money", "mcp", "silent-mutation"],
        ))

    integration_hits: list[Evidence] = []
    for relative, needle in [
        ("pkg/razorpay/integrations/backend_python.go", "int(amount * 100)"),
        ("pkg/razorpay/integrations/backend_go.go", "int(req.Amount * 100)"),
        ("pkg/razorpay/integrations/backend_java.go", "(int) (amount * 100)"),
        ("pkg/razorpay/integrations/backend_other.go", "(amount * 100).to_i"),
        ("pkg/razorpay/integrations/backend_other.go", "(req.amount * 100.0) as i64"),
        ("pkg/razorpay/integrations/backend_other.go", "(int)(request.Amount * 100)"),
    ]:
        if needle in read(repo.path / relative):
            integration_hits.append(_source_evidence(repo, relative, needle, "Generated backend uses binary float then truncates"))
    if integration_hits:
        findings.append(Finding(
            id="RP-MCP-GENERATOR-MONEY-UNDERCHARGE",
            title="Checkout generator emits one-paise undercharge bugs across seven backend languages",
            repo=repo.name,
            surface="integrate_razorpay_checkout generated backend code",
            invariant="Major-to-minor currency conversion must be decimal-exact and produce the intended integer subunit value.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="Python, Go, Java, PHP, Ruby, Rust, and .NET templates accept binary floats and truncate after multiplying by 100.",
            impact="Fresh projects generated by Razorpay's official AI tool can create orders for less than the user-entered price. The defect is copied into merchant code, multiplying its blast radius.",
            counterexample="₹2.01 is represented as 200.99999999999997 in common runtimes and becomes 200 paise.",
            proposed_fix="Make the generated boundary accept integer subunits or exact decimal strings; reject excess precision and convert with a decimal type.",
            evidence=integration_hits,
            tags=["money", "code-generation", "mcp", "cross-language", "undercharge"],
        ))

        node_backend = "pkg/razorpay/integrations/backend_node.go"
        frontend = "pkg/razorpay/integrations/frontend_templates.go"
        findings.append(Finding(
            id="RP-MCP-GENERATOR-CURRENCY-EXPONENT",
            title="Checkout generator applies a two-decimal multiplier to zero- and three-decimal currencies",
            repo=repo.name,
            surface="integrate_razorpay_checkout generated backend code",
            invariant="Major-to-minor conversion uses the exponent of the selected currency, not a hardcoded factor of 100.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="The templates accept caller-selected currency but every backend converts amount with a fixed ×100 rule. Razorpay explicitly documents JPY as zero-decimal and KWD/BHD/OMR as three-decimal currencies.",
            impact="Generated merchants can charge JPY orders at 100 times the intended value and KWD/BHD/OMR orders at roughly one tenth of the intended value. The Test API accepts and persists both wrong integer amounts because they are valid provider inputs.",
            counterexample="JPY 295 becomes 29,500; KWD 295.990 becomes 29,599/29,600 instead of 295,990.",
            proposed_fix="Accept integer currency subunits, or use an authoritative currency exponent table plus exact decimal parsing and the documented third-decimal-zero rule.",
            evidence=[
                _source_evidence(repo, node_backend, "const { amount, currency = 'INR', receipt } = req.body;", "Generated endpoint accepts arbitrary currency with a major-unit amount"),
                _source_evidence(repo, node_backend, "amount: Math.round(amount * 100)", "Generated endpoint always applies the INR-style ×100 conversion"),
                Evidence(
                    kind="provider_contract",
                    summary="Razorpay documents integer subunits with JPY exponent 0 and KWD/BHD/OMR exponent 3",
                    source_url="https://razorpay.com/docs/payments/server-integration/nodejs/integration-steps/?preferred-country=IN",
                ),
            ],
            tags=["money", "currency", "code-generation", "mcp", "cross-language", "overcharge", "undercharge"],
        ))

        findings.append(Finding(
            id="RP-MCP-GENERATOR-UNTRUSTED-ECONOMICS",
            title="Checkout generator treats browser price and cart state as the merchant's authoritative order",
            repo=repo.name,
            surface="generated order creation, verification, and checkout wiring",
            invariant="A successful payment is bound server-side to one authoritative merchant quote containing amount, currency, and cart identity.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="The generated frontend sends amount from browser state, the backend creates an order directly from that amount/currency, and the verify route checks only the browser-returned Razorpay tuple. The wiring instructions preserve the cart in localStorage rather than creating an authoritative server quote.",
            impact="A buyer can lower the browser-supplied amount, obtain and pay a valid low-value Razorpay order, and still receive a cryptographically valid success response that is not bound to the intended cart or price. Replaying a previously valid tuple is also not rejected by the generated verifier.",
            counterexample="Tamper checkout total to 1.00, pay the resulting valid order, then present its valid order_id|payment_id signature beside the untouched high-value localStorage cart.",
            proposed_fix="Create an immutable server-side quote from trusted SKU/pricing data, store its Razorpay order ID, and consume the paid tuple exactly once only after matching order, amount, currency, merchant, and fulfillment state.",
            evidence=[
                _source_evidence(repo, frontend, "body: JSON.stringify({ amount })", "Generated browser sends the price to the order endpoint"),
                _source_evidence(repo, node_backend, "const { amount, currency = 'INR', receipt } = req.body;", "Generated backend trusts browser amount and currency"),
                _source_evidence(repo, node_backend, ".update(razorpay_order_id + '|' + razorpay_payment_id)", "Verifier authenticates only the submitted Razorpay tuple"),
                _source_evidence(repo, "pkg/razorpay/integrations/helpers.go", "localStorage.setItem('pendingOrder', JSON.stringify(pendingOrder));", "Generator directs the agent to keep pending order state in browser storage"),
                Evidence(
                    kind="provider_contract",
                    summary="Razorpay says the server-created order ties the payment and secures the request from tampering",
                    source_url="https://razorpay.com/docs/payments/server-integration/nodejs/integration-steps/?preferred-country=IN",
                ),
            ],
            tags=["security", "business-logic", "price-tampering", "checkout", "code-generation", "mcp"],
        ))

        node_source = read(repo.path / node_backend)
        if "crypto.timingSafeEqual(Buffer.from(expectedSignature), Buffer.from(razorpay_signature))" in node_source:
            findings.append(Finding(
                id="RP-MCP-GENERATOR-SIGNATURE-LENGTH-500",
                title="Generated Node verifier turns malformed signature lengths into HTTP 500",
                repo=repo.name,
                surface="generated Express payment verification route",
                invariant="Untrusted malformed authentication input fails closed as a controlled client error.",
                severity=Severity.LOW,
                level=EvidenceLevel.STATIC,
                confidence=1.0,
                originality="independently discovered; no matching public issue or pull request found",
                commit=repo.commit,
                description="Node's timingSafeEqual throws when the two buffers have different lengths; the generated catch block maps that expected malformed-input path to HTTP 500.",
                impact="Any unauthenticated caller can create noisy server errors and false operational alarms on the public verify endpoint.",
                counterexample="razorpay_signature=x causes ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH and the route returns 500.",
                proposed_fix="Strictly decode a 64-character lowercase/uppercase hexadecimal signature, reject invalid length/encoding with 400, then compare equal-length bytes.",
                evidence=[
                    _source_evidence(repo, node_backend, "crypto.timingSafeEqual(Buffer.from(expectedSignature), Buffer.from(razorpay_signature))", "Generated verifier compares buffers without validating length or hex encoding"),
                    _source_evidence(repo, node_backend, "res.status(500).json({ success: false, error: 'Payment verification failed' });", "Catch block maps the thrown malformed-input path to HTTP 500"),
                ],
                tags=["error-contract", "signature", "node", "code-generation", "mcp"],
            ))

    mobile_relative = "pkg/razorpay/integrations/mobile.go"
    mobile = read(repo.path / mobile_relative)
    if (
        'put("razorpay_signature", "")' in mobile
        and '"razorpay_signature": ""' in mobile
        and "razorpay_payment_id: payment_id" in mobile
    ):
        findings.append(Finding(
            id="RP-MCP-MOBILE-MISSING-SIGNATURE",
            title="Generated Android, iOS, Cordova, and native Capacitor success paths discard the payment signature",
            repo=repo.name,
            surface="integrate_razorpay_checkout mobile code generation",
            invariant="A generated Orders API flow preserves order_id, payment_id, and razorpay_signature from Checkout through mandatory server verification.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="Android uses PaymentResultListener, which returns only payment_id, and sends an empty signature. iOS likewise chooses the no-data completion protocol and sends an empty signature. Cordova and native Capacitor use a legacy payment_id-only callback and omit the signature.",
            impact="A customer can successfully pay, after which the generated backend must reject the success callback because a mandatory verification field is absent. The merchant sees a paid-but-failed checkout and risks duplicate fulfillment recovery, support incidents, or refund churn.",
            counterexample="The generated Android and iOS request bodies contain razorpay_signature=\"\" on every successful payment.",
            proposed_fix="Use PaymentResultWithDataListener and RazorpayPaymentCompletionProtocolWithData, and use the official Cordova payment.success event/object so all three signed fields reach the backend.",
            evidence=[
                _source_evidence(repo, mobile_relative, 'put("razorpay_signature", "")', "Generated Android verification request always sends an empty signature"),
                _source_evidence(repo, mobile_relative, '"razorpay_signature": ""', "Generated iOS verification request always sends an empty signature"),
                _source_evidence(repo, mobile_relative, "razorpay_payment_id: payment_id", "Generated native Capacitor request omits razorpay_signature"),
                Evidence(
                    kind="provider_contract",
                    summary="Android PaymentResultListener returns only payment_id; WithData is required for order_id and signature",
                    source_url="https://razorpay.com/docs/payments/payment-gateway/android-integration/standard/integration-steps/?preferred-country=IN",
                ),
                Evidence(
                    kind="official_sdk_contract",
                    summary="Official Cordova Orders flow uses payment.success data containing order ID and signature",
                    source_url="https://github.com/razorpay/razorpay-cordova#orders-api-flow",
                ),
            ],
            tags=["mobile", "signature", "checkout", "code-generation", "mcp", "paid-but-failed"],
        ))
    if (
        "cordova plugin add com.nicholaswilliams.nicepay.razorpay" in mobile
        and "npm install cordova-plugin-razorpay" in mobile
    ):
        findings.append(Finding(
            id="RP-MCP-MOBILE-DEPENDENCY-CONFUSION",
            title="Mobile generator installs nonexistent or unrelated packages instead of Razorpay's official Cordova SDK",
            repo=repo.name,
            surface="Cordova, Ionic, and Capacitor dependency instructions",
            invariant="Generated payment integrations install a currently published dependency controlled by Razorpay's verified package identity.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="Cordova and Ionic emit a package name that is absent from npm. Capacitor instructs npm to install cordova-plugin-razorpay, currently an 'Empty package' maintained by a non-Razorpay account, while Razorpay's official package is com.razorpay.cordova.",
            impact="Two generated integrations fail at installation. The Capacitor path crosses a package-identity boundary and can make developers install code from a third party under a payment-SDK-like name.",
            counterexample="npm view com.nicholaswilliams.nicepay.razorpay returns E404; npm metadata identifies cordova-plugin-razorpay as an empty non-Razorpay package.",
            proposed_fix="Emit only the official com.razorpay.cordova package and supported installation instructions, pin an intentional version range, and add registry owner/repository conformance checks in CI.",
            evidence=[
                _source_evidence(repo, mobile_relative, "cordova plugin add com.nicholaswilliams.nicepay.razorpay", "Cordova and Ionic install a package absent from npm"),
                _source_evidence(repo, mobile_relative, "npm install cordova-plugin-razorpay", "Capacitor installs a similarly named non-Razorpay package"),
                Evidence(
                    kind="official_registry_identity",
                    summary="Razorpay's official Cordova package is com.razorpay.cordova",
                    source_url="https://www.npmjs.com/package/com.razorpay.cordova",
                ),
                Evidence(
                    kind="registry_identity",
                    summary="cordova-plugin-razorpay is described as an empty package and is not maintained by Razorpay",
                    source_url="https://www.npmjs.com/package/cordova-plugin-razorpay",
                ),
            ],
            tags=["security", "supply-chain", "dependency-confusion", "mobile", "code-generation", "mcp"],
        ))

    tools_params = read(repo.path / "pkg/razorpay/tools_params.go")
    if 'params["expand[]"] = val' in tools_params:
        findings.append(Finding(
            id="RP-MCP-EXPAND-COLLAPSE",
            title="Repeated expand[] values collapse to the last value",
            repo=repo.name,
            surface="collection query builder",
            invariant="Repeated query parameters preserve multiplicity and order.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.KNOWN,
            confidence=1.0,
            originality="publicly reported and source-confirmed; the linked pull request is not maintainer acceptance",
            commit=repo.commit,
            description="The loop overwrites one map key for every requested expansion.",
            impact="Callers asking for multiple expansions receive only the final expansion.",
            counterexample="expand=[payments, transfers] -> expand[]=transfers",
            proposed_fix="Represent repeated query values as a list and encode every occurrence.",
            known_reference="https://github.com/razorpay/razorpay-mcp-server/pull/108",
            evidence=[_source_evidence(repo, "pkg/razorpay/tools_params.go", 'params["expand[]"] = val', "Each loop iteration overwrites the same key")],
            tags=["query", "multiplicity", "known"],
        ))

    if "X-Refund-Idempotency" not in refunds and '"receipt"' in refunds:
        findings.append(Finding(
            id="RP-MCP-REFUND-IDEMPOTENCY",
            title="Refund tool omits header idempotency and hides receipt safety semantics",
            repo=repo.name,
            surface="create_refund MCP tool",
            invariant="A retryable money-moving action exposes and preserves effect identity.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.KNOWN,
            confidence=1.0,
            originality="publicly reported safety gap; the linked pull request is not maintainer acceptance",
            commit=repo.commit,
            description="The tool cannot send X-Refund-Idempotency and describes receipt only as an internal reference, even though Razorpay documents a stable receipt as an idempotency key.",
            impact="A caller that omits receipt can create another refund on retry by design. A caller that reuses a stable receipt already has duplicate protection, so this is a safety/discoverability gap rather than a broken refund API.",
            counterexample="No identity is intentionally a new refund; stable receipt or X-Refund-Idempotency identifies one effect.",
            proposed_fix="Document receipt as the existing idempotency mechanism and also expose X-Refund-Idempotency for explicit retry identity.",
            known_reference="https://github.com/razorpay/razorpay-mcp-server/pull/128",
            evidence=[
                _source_evidence(repo, "pkg/razorpay/refunds.go", 'mcpgo.WithString(\n\t\t\t"receipt",', "Tool exposes receipt but describes it only as internal reference"),
                _source_evidence(repo, "pkg/razorpay/refunds.go", 'int(payload["amount"].(float64)), data, nil)', "Refund SDK call passes nil headers"),
            ],
            tags=["money", "idempotency", "agent-retry", "known"],
            claim_kind=ClaimKind.SAFETY_GAP,
        ))

    readme = read(repo.path / "README.md")
    payouts = read(repo.path / "pkg/razorpay/payouts.go")
    if "fetch_payout_by_id" in readme and "fetch_payout_with_id" in payouts:
        findings.append(Finding(
            id="RP-MCP-PAYOUT-NAME-DRIFT",
            title="Published payout tool name does not exist",
            repo=repo.name,
            surface="MCP README/tool registry",
            invariant="Published tool identifiers match the registered interface exactly.",
            severity=Severity.LOW,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered",
            commit=repo.commit,
            description="README advertises fetch_payout_by_id while the server registers fetch_payout_with_id.",
            impact="An agent following the official interface table calls a nonexistent tool.",
            proposed_fix="Rename the registered tool or update the table and add a docs-to-registry conformance test.",
            evidence=[
                _source_evidence(repo, "README.md", "fetch_payout_by_id", "Published name"),
                _source_evidence(repo, "pkg/razorpay/payouts.go", '"fetch_payout_with_id"', "Registered name"),
            ],
            tags=["interface-drift", "mcp", "docs"],
            claim_kind=ClaimKind.DOCUMENTATION,
        ))
    return findings


def _dotnet(repo: Repository) -> list[Finding]:
    relative = "src/Utils.cs"
    source = read(repo.path / relative)
    findings: list[Finding] = []
    if "new ASCIIEncoding()" in source:
        findings.append(Finding(
            id="RP-DOTNET-WEBHOOK-ASCII",
            title=".NET webhook verifier hashes non-ASCII strings as ASCII",
            repo=repo.name,
            surface="Utils.verifyWebhookSignature",
            invariant="HMAC input is the exact UTF-8 request body, byte for byte.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public report found",
            commit=repo.commit,
            description="The SDK's central StringEncode helper is ASCIIEncoding, so names, notes, and descriptions in Indian scripts or emoji become question marks.",
            impact="A correct UTF-8 signature is rejected for ordinary Razorpay Test Mode payment-link and refund deliveries containing literal non-ASCII metadata.",
            counterexample='payload={"name":"Achu ₹ മലയാളം"}: Razorpay signs UTF-8; SDK hashes ASCII substitutions.',
            proposed_fix="Expose a byte[] webhook API and use UTF-8 explicitly for string compatibility overloads.",
            evidence=[_source_evidence(repo, relative, "new ASCIIEncoding()", "All signature strings are encoded as ASCII")],
            tags=["webhook", "unicode", "cryptography", "dotnet"],
            claim_kind=ClaimKind.DEFECT,
        ))
    if "Array.Copy(keyBytes, 0, iv, 0, 12)" in source:
        findings.append(Finding(
            id="RP-DOTNET-GCM-NONCE-REUSE",
            title=".NET onboarding signatures reuse an AES-GCM nonce derived from the secret key",
            repo=repo.name,
            surface="Utils.GenerateOnboardingSignature",
            invariant="AES-GCM uses a fresh unique nonce for every encryption under a key.",
            severity=Severity.CRITICAL,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered cross-SDK regression; Ruby, Node, Java and PHP already shipped the random-nonce fix",
            commit=repo.commit,
            description="The first 12 key bytes are copied into the IV, making every encryption under one secret reuse the same GCM nonce.",
            impact="Nonce reuse breaks AES-GCM confidentiality and authentication guarantees; repeated onboarding signatures become deterministic and related plaintexts leak keystream relations.",
            counterexample="Encrypting identical onboarding JSON twice under one secret returns identical ciphertext.",
            proposed_fix="Generate 12 random bytes per call and return nonce || ciphertext || 16-byte tag, matching the other current SDKs.",
            evidence=[
                _source_evidence(repo, relative, "Array.Copy(keyBytes, 0, iv, 0, 12)", "IV is deterministically copied from the key"),
                Evidence(kind="cross_sdk_release", summary="Ruby release documents the same nonce-reuse defect and fixed wire format", source_url="https://github.com/razorpay/razorpay-ruby/releases/tag/v3.2.4"),
            ],
            tags=["cryptography", "aes-gcm", "nonce-reuse", "cross-sdk"],
        ))
    if "actualSignature.Equals(expectedSignature)" in source:
        findings.append(Finding(
            id="RP-DOTNET-SIGNATURE-COMPARE",
            title=".NET signature verification uses ordinary string equality",
            repo=repo.name,
            surface="Utils.verifySignature",
            invariant="Authentication tags are compared in constant time.",
            severity=Severity.LOW,
            level=EvidenceLevel.KNOWN,
            confidence=0.98,
            originality="publicly proposed hardening and independently source-confirmed; no practical remote exploit reproduced",
            commit=repo.commit,
            description="The verifier uses String.Equals rather than a fixed-time byte comparison.",
            impact="Ordinary equality is functionally correct. A fixed-time comparison reduces timing leakage, but practical remote exploitability was not reproduced or claimed.",
            proposed_fix="Decode hex and call CryptographicOperations.FixedTimeEquals.",
            known_reference="https://github.com/razorpay/razorpay-dot-net/pull/153",
            evidence=[_source_evidence(repo, relative, "actualSignature.Equals(expectedSignature)", "Non-constant-time comparison")],
            tags=["cryptography", "timing", "dotnet"],
            claim_kind=ClaimKind.HARDENING,
        ))

    client_relative = "src/RazorpayClient.cs"
    client_source = read(repo.path / client_relative)
    rest_relative = "src/RestClient.cs"
    rest_source = read(repo.path / rest_relative)
    if (
        "private static string key" in client_source
        and "private static string secret" in client_source
        and "RazorpayClient.Key" in rest_source
        and "RazorpayClient.Secret" in rest_source
    ):
        findings.append(Finding(
            id="RP-DOTNET-GLOBAL-AUTH-STATE",
            title=".NET client instances overwrite one process-wide credential and routing context",
            repo=repo.name,
            surface="RazorpayClient, RestClient, and payment signature verification",
            invariant="Credentials, base URL, access token, and request headers are scoped to one client instance and cannot be changed by constructing another client.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="The public client stores key, secret, base URL, access token, application details, and headers in static fields. Constructors overwrite them, while requests and payment verification read those global fields later.",
            impact="A multi-tenant or multi-account .NET process can authenticate client A's request as client B, route it with another account's X-Razorpay-Account header, or reject A's valid payment signature after B is initialized.",
            counterexample="Construct client A, then client B; client A's subsequent request and Utils.verifyPaymentSignature use B's static key/secret.",
            proposed_fix="Make all authentication, endpoint, header, and utility state immutable instance fields; bind resource clients and verification calls to an explicit client or secret.",
            evidence=[
                _source_evidence(repo, client_relative, "private static string key = null;", "API key is process-global"),
                _source_evidence(repo, client_relative, "private static string secret = null;", "API secret is process-global"),
                _source_evidence(repo, client_relative, "protected static Dictionary<string, string> headers", "Partner routing and custom headers are process-global"),
                _source_evidence(repo, rest_relative, "string authString = string.Format(\"{0}:{1}\", RazorpayClient.Key, RazorpayClient.Secret);", "Every request reads current global credentials"),
                _source_evidence(repo, relative, "string secret = RazorpayClient.Secret;", "Payment verification reads the current global secret"),
            ],
            tags=["security", "multi-tenant", "credentials", "partner-routing", "dotnet", "global-state"],
        ))
    return findings


def _php(repo: Repository) -> list[Finding]:
    api_relative = "src/Api.php"
    request_relative = "src/Request.php"
    api = read(repo.path / api_relative)
    request = read(repo.path / request_relative)
    if not (
        "protected static $key" in api
        and "protected static $secret" in api
        and "Api::getKey()" in request
        and "protected static $headers" in request
    ):
        return []
    return [Finding(
        id="RP-PHP-GLOBAL-AUTH-STATE",
        title="PHP client instances share and overwrite process-wide credentials and headers",
        repo=repo.name,
        surface="Api and Request authentication state",
        invariant="Each SDK client owns immutable credentials, base URL, token, and headers for its requests.",
        severity=Severity.HIGH,
        level=EvidenceLevel.STATIC,
        confidence=1.0,
        originality="independently discovered; no matching public issue or pull request found",
        commit=repo.commit,
        description="Api stores key, secret, OAuth token, base URL, and app details statically; Request also stores headers statically and resolves authentication from Api at request time. Api-created resources retain no owner client.",
        impact="Long-running PHP workers serving multiple merchants can send one merchant's operation under another merchant's credentials or partner routing header, crossing account and tenant boundaries.",
        counterexample="Construct Api A and keep its Order resource, construct Api B, then call the A resource; Request reads B's static credentials.",
        proposed_fix="Move authentication, base URL, app details, and headers to instance-owned request clients, and inject that request client into every resource.",
        evidence=[
            _source_evidence(repo, api_relative, "protected static $key = null;", "API key is process-global"),
            _source_evidence(repo, api_relative, "self::$key = $key;", "Each constructor overwrites the process-global key"),
            _source_evidence(repo, api_relative, "$entity = new $className();", "Resources are created without an owning client context"),
            _source_evidence(repo, request_relative, "$options['auth'] = array(Api::getKey(), Api::getSecret());", "Requests resolve the latest global credentials at call time"),
            _source_evidence(repo, request_relative, "protected static $headers = array(", "Request headers are process-global"),
        ],
        tags=["security", "multi-tenant", "credentials", "partner-routing", "php", "global-state"],
    )]


def _java_semantics(repo: Repository) -> list[Finding]:
    findings: list[Finding] = []
    client_relative = "src/main/java/com/razorpay/RazorpayClient.java"
    api_relative = "src/main/java/com/razorpay/ApiUtils.java"
    client = read(repo.path / client_relative)
    api = read(repo.path / api_relative)
    if (
        "private static Map<String, String> headers" in api
        and "ApiUtils.addHeaders(headers);" in client
        and "for (Map.Entry<String, String> header : headers.entrySet())" in api
    ):
        findings.append(Finding(
            id="RP-JAVA-GLOBAL-PARTNER-HEADERS",
            title="Java clients share one process-wide partner-routing header map",
            repo=repo.name,
            surface="RazorpayClient.addHeaders and ApiUtils.createRequest",
            invariant="X-Razorpay-Account and custom headers are scoped to the intended client or request.",
            severity=Severity.HIGH,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="Credentials are resource-scoped, but addHeaders mutates a static map that every client request reads. No public remove/reset or per-request isolation exists.",
            impact="In an aggregator process, setting X-Razorpay-Account for one sub-merchant can silently route later requests from every other client to that same sub-merchant.",
            counterexample="clientA.addHeaders(X-Razorpay-Account=A); clientB.addHeaders(...=B); both subsequent requests carry B.",
            proposed_fix="Store immutable default headers per RazorpayClient/resource and support per-request overrides; never use a mutable static routing map.",
            evidence=[
                _source_evidence(repo, api_relative, "private static Map<String, String> headers", "All Java client instances share one header map"),
                _source_evidence(repo, client_relative, "ApiUtils.addHeaders(headers);", "Instance method writes the global header map"),
                _source_evidence(repo, api_relative, "for (Map.Entry<String, String> header : headers.entrySet())", "Every request reads the global header map"),
                Evidence(
                    kind="provider_contract",
                    summary="Razorpay uses X-Razorpay-Account to select the sub-merchant for partner API calls",
                    source_url="https://razorpay.com/docs/partners/aggregators/partner-auth/?preferred-country=IN",
                ),
            ],
            tags=["security", "multi-tenant", "partner-routing", "java", "global-state"],
        ))
    if 'extenionName == "jpg"' in api:
        findings.append(Finding(
            id="RP-JAVA-UPLOAD-MIME",
            title="Java document uploads mislabel runtime JPG and PNG paths as PDF",
            repo=repo.name,
            surface="ApiUtils.getMediaType",
            invariant="Multipart file MIME type matches the selected file format.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="The extension extracted with substring is compared using Java reference equality, so ordinary runtime jpg/jpeg/png/jfif strings fall through to image/pdf.",
            impact="Valid evidence and KYC image uploads can be rejected, misclassified, or processed through the wrong media path.",
            counterexample='getMediaType("proof.png") returns image/pdf rather than image/png.',
            proposed_fix="Use equalsIgnoreCase, map each supported extension to its documented MIME type, reject unknown extensions, and preferably inspect trusted content metadata.",
            evidence=[
                _source_evidence(repo, api_relative, 'if(extenionName == "jpg" | extenionName == "jpeg" | extenionName == "png" | extenionName == "jfif")', "Runtime strings are compared with reference equality and non-short-circuit OR"),
                _source_evidence(repo, api_relative, 'return "image/pdf";', "All failed image comparisons fall through to image/pdf"),
                Evidence(
                    kind="provider_contract",
                    summary="Document API documents image/jpg, image/jpeg, image/png, and application/pdf",
                    source_url="https://razorpay.com/docs/api/documents/create/?preferred-country=IN",
                ),
            ],
            tags=["documents", "multipart", "mime", "java"],
        ))
    if (
        'multipartBodyBuilder.addFormDataPart("file",fileName, fileBody);' in api
        and "Iterator<?> iterator = requestObject.keys();" in api
    ):
        findings.append(Finding(
            id="RP-JAVA-UPLOAD-DUPLICATE-FILE-PART",
            title="Java document upload serializes the file field twice with conflicting types",
            repo=repo.name,
            surface="ApiUtils.fileRequestBody",
            invariant="The singular document file field appears exactly once as a binary multipart part.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.STATIC,
            confidence=1.0,
            originality="independently discovered; no matching public issue or pull request found",
            commit=repo.commit,
            description="The SDK first adds file as a binary part, then iterates every request key without excluding file and adds the filesystem path as a second text part with the same name.",
            impact="Servers and intermediaries can select the wrong duplicate field, reject the request, or treat a local pathname as the uploaded file value.",
            counterexample='{"file":"/tmp/proof.png","purpose":"dispute_evidence"} emits two name="file" parts.',
            proposed_fix="Remove file from the ordinary field loop and serialize it exactly once as the binary part; add a wire-format cardinality test.",
            evidence=[
                _source_evidence(repo, api_relative, 'multipartBodyBuilder.addFormDataPart("file",fileName, fileBody);', "SDK adds the binary file part"),
                _source_evidence(repo, api_relative, "Iterator<?> iterator = requestObject.keys();", "SDK then iterates all fields including file"),
                _source_evidence(repo, api_relative, "multipartBodyBuilder.addFormDataPart((String) key, (String) value);", "SDK adds file path again as a text part"),
            ],
            tags=["documents", "multipart", "cardinality", "java"],
        ))
    return findings


def _ruby(repo: Repository) -> list[Finding]:
    relative = "lib/razorpay/utility.rb"
    source = read(repo.path / relative)
    if "attributes.values.join('|')" not in source:
        return []
    return [Finding(
        id="RP-RUBY-PAYLINK-ORDER",
        title="Ruby payment-link verification depends on Hash insertion order",
        repo=repo.name,
        surface="Utility.verify_payment_link_signature",
        invariant="The signed field order is protocol-defined, not caller-container-defined.",
        severity=Severity.MEDIUM,
        level=EvidenceLevel.STATIC,
        confidence=1.0,
        originality="independently discovered; no matching public issue or pull request found",
        commit=repo.commit,
        description="The SDK deletes the signature and joins every remaining Hash value in insertion order.",
        impact="An authentic callback fails verification when the application builds the same field set in a different order; extra fields also contaminate the signature payload.",
        counterexample="Correct fields inserted as payment_id, status, link_id, reference_id fail; docs-order insertion passes.",
        proposed_fix="Read the four named fields explicitly in the protocol-defined order and do not mutate the caller's Hash.",
        evidence=[_source_evidence(repo, relative, "attributes.values.join('|')", "Signature payload follows Hash insertion order")],
        tags=["payment-link", "signature", "ruby", "order-dependence"],
    )]


def _python(repo: Repository) -> list[Finding]:
    relative = "razorpay/utility/utility.py"
    source = read(repo.path / relative)
    findings: list[Finding] = []
    if "body = bytes(body, 'utf-8')" in source:
        findings.append(Finding(
            id="RP-PYTHON-WEBHOOK-BYTES",
            title="Python webhook verifier rejects the raw bytes the webhook contract asks callers to preserve",
            repo=repo.name,
            surface="Utility.verify_webhook_signature",
            invariant="Valid raw request bytes are accepted without decoding and re-encoding.",
            severity=Severity.MEDIUM,
            level=EvidenceLevel.KNOWN,
            confidence=1.0,
            originality="publicly reported compatibility issue and independently source-confirmed; not maintainer-confirmed",
            commit=repo.commit,
            description="bytes(body, 'utf-8') raises TypeError when body is already bytes.",
            impact="Framework integrations that correctly retain the raw body cannot pass it to the SDK.",
            proposed_fix="Encode str inputs and preserve bytes/bytearray inputs.",
            known_reference="https://github.com/razorpay/razorpay-python/issues/121",
            evidence=[_source_evidence(repo, relative, "body = bytes(body, 'utf-8')", "Unconditional str-to-bytes constructor")],
            tags=["webhook", "raw-bytes", "python", "known"],
            claim_kind=ClaimKind.COMPATIBILITY,
        ))
    if "payment_link_id = str(parameters['payment_link_id'])" in source:
        findings.append(Finding(
            id="RP-PYTHON-PAYLINK-MISSING-FIELD",
            title="Python payment-link verifier throws KeyError for an omitted field it forgot to validate",
            repo=repo.name,
            surface="Utility.verify_payment_link_signature",
            invariant="Incomplete verification input fails closed with one documented result.",
            severity=Severity.LOW,
            level=EvidenceLevel.KNOWN,
            confidence=1.0,
            originality="publicly proposed fix and independently source-confirmed; the pull request is not maintainer acceptance",
            commit=repo.commit,
            description="The guard checks three fields, omits payment_link_id and razorpay_signature, then indexes both.",
            impact="Malformed callback handling can become an application 500 rather than a clean authentication rejection.",
            proposed_fix="Validate the complete required field set before access.",
            known_reference="https://github.com/razorpay/razorpay-python/pull/333",
            evidence=[_source_evidence(repo, relative, "payment_link_id = str(parameters['payment_link_id'])", "Unchecked required field access")],
            tags=["payment-link", "error-contract", "python", "known"],
        ))
    return findings


def _other_crypto(repositories: dict[str, Repository]) -> list[Finding]:
    findings: list[Finding] = []
    node = repositories.get("razorpay-node")
    if node:
        relative = "lib/utils/razorpay-utils.js"
        source = read(node.path / relative)
        if "expectedSignature === signature" in source:
            findings.append(Finding(
                id="RP-NODE-SIGNATURE-COMPARE",
                title="Node webhook verifier uses ordinary string equality",
                repo=node.name,
                surface="validateWebhookSignature",
                invariant="Authentication tags are compared in constant time.",
                severity=Severity.LOW,
                level=EvidenceLevel.KNOWN,
                confidence=0.98,
                originality="publicly reported hardening concern; no maintainer confirmation or practical exploit reproduction",
                commit=node.commit,
                description="The SDK compares hex HMACs with JavaScript strict equality.",
                impact="Strict equality is functionally correct. A timing-safe comparison is defensive hardening; practical remote exploitability was not reproduced or claimed.",
                proposed_fix="Use crypto.timingSafeEqual after strict length and hex validation.",
                known_reference="https://github.com/razorpay/razorpay-node/issues/479",
                evidence=[_source_evidence(node, relative, "expectedSignature === signature", "Non-constant-time comparison")],
                tags=["cryptography", "timing", "node", "known"],
                claim_kind=ClaimKind.HARDENING,
            ))
    java = repositories.get("razorpay-java")
    if java:
        relative = "src/main/java/com/razorpay/Utils.java"
        source = read(java.path / relative)
        if "sha256_HMAC.doFinal(payload.getBytes())" in source:
            findings.append(Finding(
                id="RP-JAVA-DEFAULT-CHARSET",
                title="Java webhook HMAC payload uses the process default charset",
                repo=java.name,
                surface="Utils.getHash",
                invariant="String compatibility APIs encode exact UTF-8 deterministically.",
                severity=Severity.MEDIUM,
                level=EvidenceLevel.KNOWN,
                confidence=1.0,
                originality="publicly reported compatibility issue and independently source-confirmed; not maintainer-confirmed",
                commit=java.commit,
                description="The secret is explicitly UTF-8 but the payload calls getBytes() with no charset.",
                impact="Unicode verification can depend on host locale on Java versions/configurations with a non-UTF-8 default. Java 18+ defaults to UTF-8, so this is conditional rather than universal.",
                proposed_fix="Use StandardCharsets.UTF_8 and add a byte[] verifier.",
                known_reference="https://github.com/razorpay/razorpay-java/issues/351",
                evidence=[_source_evidence(java, relative, "sha256_HMAC.doFinal(payload.getBytes())", "Default-charset payload encoding")],
                tags=["webhook", "unicode", "java", "known"],
                claim_kind=ClaimKind.COMPATIBILITY,
            ))
    return findings


def run_static_probes(repositories: dict[str, Repository]) -> list[ProbeResult]:
    results: list[ProbeResult] = []
    with ProbeTimer("static:mcp-semantic-contracts") as result:
        if repo := repositories.get("razorpay-mcp-server"):
            result.findings.extend(_mcp(repo))
        else:
            result.errors.append("razorpay-mcp-server repository missing")
    results.append(result)
    with ProbeTimer("static:sdk-cryptographic-contracts") as result:
        if repo := repositories.get("razorpay-dot-net"):
            result.findings.extend(
                finding for finding in _dotnet(repo)
                if finding.id != "RP-DOTNET-GLOBAL-AUTH-STATE"
            )
        if repo := repositories.get("razorpay-ruby"):
            result.findings.extend(_ruby(repo))
        if repo := repositories.get("razorpay-python"):
            result.findings.extend(_python(repo))
        result.findings.extend(_other_crypto(repositories))
    results.append(result)
    with ProbeTimer("static:sdk-client-and-multipart-contracts") as result:
        if repo := repositories.get("razorpay-dot-net"):
            result.findings.extend(
                finding for finding in _dotnet(repo)
                if finding.id == "RP-DOTNET-GLOBAL-AUTH-STATE"
            )
        if repo := repositories.get("razorpay-php"):
            result.findings.extend(_php(repo))
        if repo := repositories.get("razorpay-java"):
            result.findings.extend(_java_semantics(repo))
    results.append(result)
    return results
